[package]
name = "pyrustpipe"
version = "0.1.0"
edition = "2024"

[lib]
name="pyrustpipe"
crate-type = ["cdylib"]


[dependencies]
pyo3 ={ version = "0.22", features = ["extension-module"] }
regex = "1.11.1"